# This file configures github.com/golangci/golangci-lint.

run:
  timeout: 2m
  tests: true
  skip-dirs-use-default: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck

issues:
  exclude-rules:
    - text: "comment on exported var"
      linters:
        - golint
    - text: "ST1005:"
      linters:
        - stylecheck