[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  # TODO: Remove this forked source and branch once Turbo-Geth is ready as a
  # client.
  source = "github.com/alexanderbez/go-ethereum"
  branch = "ethermint-statedb"

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  # TODO: Remove this once 0.25 has been released
  revision = "075ddce79acb77fe88f849f93fb3036e48ffb555"
  # version = "=0.24.2"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  revision = "0fb14efe8c47ae851c0034ed7a448854d3d34cf3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.1"

[[constraint]] 
  name = "github.com/pkg/errors"
  version = "=0.8.0"

# dependecy overrides

[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.11.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.25.1-rc0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "=v0.12.0"

[prune]
  go-tests = true
