[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  # TODO: Replace with a stable tagged version
  branch = "develop"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[[constraint]]
  version = "=0.22.0-rc2"
  name = "github.com/tendermint/tendermint"

[prune]
  go-tests = true
