[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "0.19.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.11"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.22.0-rc2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "~1.0.0"

[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"

[prune]
  go-tests = true
  unused-packages = true
