version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/cosmos/ethermint

    steps:
      - checkout
      - run: make tools deps
      - run: make test-lint test-unit
